image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - develop
    - qa

develop:
    stage: develop
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_DEVELOP --api-key=$HEROKU_API_KEY
    only:
        - develop

qa:
    stage: qa
    image: ruby:latest
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_QA --api-key=$HEROKU_API_KEY
    only:
        - qa
