export const white = {
    fontColor: {
        lightBlue: '#B3DAFE',
        blue: '#027EF4',
        darkBlue: '#1F6FA9',
        white: '#FFFFFF',
        lightGray: '#838A91',
        darkestGray: '#373E40',
        swxBlack: '#030303',
        mediumGreen: '#1DB304',
        swxSlightlyBlack: '#000A14',
        red: '#F43C02',
    },
    backgroundColor: {
        darkBlue: '#1B6397',
        blue: '#1F6FA9',
        white: '#FFFFFF',
        lightGray: '#E6E8E9',
        lighterGray: '#F1F1F1',
        lightestGray: '#F7F7F8',
        lightGreen: '#D8FED2',
        lightRed: '#FFE0D7',
        lightBlue: '#DCEEFF',
    },
    borderColor: {
        blue: '#027EF4',
        lightGray: '#E6E8E9',
    },
    borderRadius: {
        large: '100px',
        verySmall: '5px',
        small: '8px',
    },
    fontSize: {
        smallest: '12px',
        small: '14px',
        smallOdd: '15px',
        semiMedium: '16px',
        medium: '18px',
        semiLarge: '20px',
        large: '24px',
        extraLarge: '28px',
        largest: '56px',
    },
    fontWeight: {
        extraThin: '400',
        thin: '500',
        semiBold: '600',
        bold: '700',
    },
    boxShadow: {
        whiteShadow: '0px 2px 9px rgba(3, 3, 3, 0.16)',
        grayShadow: '0px 1px 2px 0px rgba(6, 21, 35, 0.12)',
        blueShadow: '0px 0px 0px 2px rgba(2, 126, 244, 0.20)',
        darkBlueShadow: '0px 2px 0px 0px #17527D',
    },
};
